/**
 * @type {array} @name phraseStrings array of strings 
 */
const phraseStrings = [
    'Once in a blue moon',
    'Piece of cake',
    'Raining cats and dogs',
    'When pigs fly',
    'Poke the bear',
    'Blow off steam',
    'Throw in the towel',
    'A shot in the dark',
    'Let the cat out of the bag',
    'Back against a wall',
    'Saved by the bell',
    'Break a leg',
    'Barking up the wrong tree',
    'Spill the beans',
    'Under the weather', 
    'Bit the bullet', 
    'All bark and no bite',
    'Two birds one stone',
    'A short fuse',
    'Draw the line',
    'Easier said than done',
    'Needle in a haystack',
    'Fish out of water', 
    'Give it a whirl',
    'Go the extra mile', 
    'Hang in there', 
    'Lose your marbles', 
    'Play second fiddle',
    'Sick and tired', 
    'Pull yourself together',
    'Sleep on it', 
    'Tip of the iceberg', 
    'Take it easy',
    'Ants in your pants', 
    'Elephant in the room', 
    'Ducks in a row', 
    'Hair of the dog', 
    'Hold your horses', 
    'Lipstick on a pig', 
    'Quit cold turkey', 
    'Behind the eight ball', 
    'Ahead of the game', 
    'Get the ball rolling', 
    'Down to the wire', 
    'Dead ringer', 
    'Out of your league', 
    'Go to the Mattresses', 
    'Toe the line',
    'Elbow grease', 
    'Bundle of nerves',
    'Lend me your ears',
    'Belly up', 
    'Joined at the hip', 
    'Long in the tooth',
    'Elbow room',
    'Pick your brain', 
    'No skinn off my nose', 
    'Slap on the wrist',
    'Stick your neck out', 
    'Your neck of the woods',
    'A dime a dozen', 
    'Bought the farm', 
    'Jump on the bandwagon', 
    'Pass the buck', 
    'Shoot the breeze',
    'Hit the sack', 
    'Hit the hay', 
    'Put a pin in it',
    'Take a rain check',
    'Foot in the door', 
    'Like pulling teeth',
    'Icing on the cake',
    'Worst come to worst',
    'In a jam',
    'In a pinch',
    'In a pickle',
    'In a bind',
    'Play your cards right',
    'In a rut', 
    'In full swing',
    'In my book', 
    'In my element',
    'In seventh heaven', 
    'In the bag', 
    'In the doghouse',
    'In the long run',
    'In the nick of time',
    'Takes one to know one',
    'Crunch time',
    'Rocket science',
    'Brain surgery',
    'Joined at the hip',
    'Jump through hoops',
    'Jump the gun',
    'Jury is still out',
    'Head above water',
    'Keep your cool',
    'Keep in the loop',
    'Keep me posted', 
    'Nose to the grindstone',
    'Keep at bay',
    'Keep your nose clean',
    'Kill the mood',
    'Kit and caboodle',
    'Knock on wood',
    'Knock if off',
    'Know the ropes',
    'Labor of love',
    'Last but not least',
    'Lap of luxury',
    'The last straw',
    'Laugh to the bank',
    'Lay down the law'
];